---
driver:
  name: docker
driver_config:
  use_sudo: false
  socket: tcp://192.168.59.103:2376
  require_chef_omnibus: 12.0.3
  http_proxy: http://192.168.1.167:3128
  https_proxy: http://192.168.1.167:3128
  #provision_command: "curl -L https://www.opscode.com/chef/install.sh | bash"
  forward:
  - 8080:80

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[docker-registry2::default]
    attributes:
