---
driver:
  name: docker
driver_config:
  http_proxy: <%= ENV.fetch('http_proxy', "http://172.17.42.1:3128") %>
  https_proxy: <%= ENV.fetch('https_proxy', "https://172.17.42.1:3128") %>
  instance_name: <%= ENV.fetch('INSTANCE_NAME', "docker-regristry2") %>
  use_sudo: false
  privileged: true
  remove_images: false
  image: denny/osc:latest
  tls_verify: true
  tls_cacert: /Users/mac/Dropbox/private_data/project/docker/docker_tls_oscgc/ca.pem
  tls_cert: /Users/mac/Dropbox/private_data/project/docker/docker_tls_oscgc/cert.pem
  tls_key: /Users/mac/Dropbox/private_data/project/docker/docker_tls_oscgc/key.pem
  socket: tcp://192.168.1.185:4243
  provision_command: "curl -L https://raw.githubusercontent.com/DennyZhang/data/master/denny_chef_provision.sh | bash -e"
  forward:
  - 8080:8080

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[docker-registry2::default]
    attributes:
        {docker_registry2:
                {username: 'mydocker',
                 password: 'dockerpasswd',
                 domain_name: 'www.testdocker.com',
                 server_ip: '127.0.0.1'
                }}
