---
driver:
  name: docker
driver_config:
  use_sudo: false
  socket: tcp://192.168.59.103:2376
  provision_command: "curl -L https://www.opscode.com/chef/install.sh | bash"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[docker-registry2::default]
    attributes:
